/* Generated by itemis CREATE code generator. */

#ifndef STATECHART_REQUIRED_H_
#define STATECHART_REQUIRED_H_

#include "sc_types.h"
#include "Statechart.h"

#ifdef __cplusplus
extern "C"
{
#endif 

/*! \file
This header defines prototypes for all functions that are required by the state machine implementation.

This state machine makes use of operations declared in the state machines interface or internal scopes. Thus the function prototypes:
- statechartIface_print
- statechartIface_reset
- statechartIface_sistema_autotest_ok
are defined.

These functions will be called during a 'run to completion step' (runCycle) of the statechart. 
There are some constraints that have to be considered for the implementation of these functions:
- make sure that the execution time is as short as possible.
*/
extern void statechartIface_print( Statechart* handle, const sc_string Mensaje);
extern void statechartIface_reset( Statechart* handle);
extern sc_boolean statechartIface_sistema_autotest_ok( Statechart* handle);




#ifdef __cplusplus
}
#endif 

#endif /* STATECHART_REQUIRED_H_ */
