/* Generated by itemis CREATE code generator. */

#ifndef STATECHART_H_
#define STATECHART_H_

#ifdef __cplusplus
extern "C" { 
#endif

/*!
* Forward declaration for the Statechart state machine.
*/
typedef struct Statechart Statechart;

/*!
* Forward declaration of the data structure for the StatechartIface interface scope.
*/
typedef struct StatechartIface StatechartIface;

#ifdef __cplusplus
}
#endif

#include "sc_types.h"

#ifdef __cplusplus
extern "C" { 
#endif 

/*! \file
Header of the state machine 'Statechart'.
*/

#ifndef STATECHART_EVENTQUEUE_BUFFERSIZE
#define STATECHART_EVENTQUEUE_BUFFERSIZE 20
#endif
#ifndef STATECHART_IN_EVENTQUEUE_BUFFERSIZE
#define STATECHART_IN_EVENTQUEUE_BUFFERSIZE STATECHART_EVENTQUEUE_BUFFERSIZE
#endif
#ifndef SC_INVALID_EVENT_VALUE
#define SC_INVALID_EVENT_VALUE 0
#endif
/*! Define number of states in the state enum */
#define STATECHART_STATE_COUNT 11

/*! Define dimension of the state configuration vector for orthogonal states. */
#define STATECHART_MAX_ORTHOGONAL_STATES 1

/*! Define indices of states in the StateConfVector */
#define SCVI_STATECHART_MAIN_REGION_STATE_OFF 0
#define SCVI_STATECHART_MAIN_REGION_STATE_SAVE_ENERGY 0
#define SCVI_STATECHART_MAIN_REGION_STATE_FABRICANTE 0
#define SCVI_STATECHART_MAIN_REGION_STATE_FABRICANTE_R1_STATE_DIAGNOSTICO 0
#define SCVI_STATECHART_MAIN_REGION_STATE_FABRICANTE_R1_STATE_AJUSTE_TEMP_DESEADA 0
#define SCVI_STATECHART_MAIN_REGION_STATE_FABRICANTE_R1_STATE_STOCK_AJUSTE 0
#define SCVI_STATECHART_MAIN_REGION_STATE_MENU_PRINCIPAL 0
#define SCVI_STATECHART_MAIN_REGION_STATE_BREWING 0
#define SCVI_STATECHART_MAIN_REGION_STATE_SELECCION_CAFE 0
#define SCVI_STATECHART_MAIN_REGION_STATE_CAFE_PERSONALIZADO 0
#define SCVI_STATECHART_MAIN_REGION_STATE_ERRROR 0


/* 
 * Enum of event names in the statechart.
 */
typedef enum  {
	Statechart_invalid_event = SC_INVALID_EVENT_VALUE,
	Statechart_EVENT_JOY_UP,
	Statechart_EVENT_JOY_DOWN,
	Statechart_EVENT_JOY_LEFT,
	Statechart_EVENT_TIMEOUT,
	Statechart_EVENT_BUTTON1_EDGE,
	Statechart_EVENT_BUTTON1,
	Statechart_EVENT_BUTTON3,
	Statechart_LED_PERSONALIZADO_START,
	Statechart_LED_RECIENTE_START,
	Statechart_LED_DOBLE_START,
	Statechart_LED_LATTE_START,
	Statechart_LED_MOCHA_START,
	Statechart_EVENT_NONE
} StatechartEventID;

/*
 * Struct that represents a single event.
 */
typedef struct {
	StatechartEventID name;
} statechart_event;

/*
 * Queue that holds the raised events.
 */
typedef struct statechart_eventqueue_s {
	statechart_event *events;
	sc_integer capacity;
	sc_integer pop_index;
	sc_integer push_index;
	sc_integer size;
} statechart_eventqueue;

/*! Enumeration of all states */ 
typedef enum
{
	Statechart_last_state,
	statechart_main_region_State_OFF,
	statechart_main_region_State_SAVE_ENERGY,
	statechart_main_region_State_FABRICANTE,
	statechart_main_region_State_FABRICANTE_r1_State_DIAGNOSTICO,
	statechart_main_region_State_FABRICANTE_r1_State_AJUSTE_TEMP_DESEADA,
	statechart_main_region_State_FABRICANTE_r1_State_STOCK_AJUSTE,
	statechart_main_region_State_MENU_PRINCIPAL,
	statechart_main_region_State_BREWING,
	statechart_main_region_State_SELECCION_CAFE,
	statechart_main_region_State_CAFE_PERSONALIZADO,
	statechart_main_region_State_ERRROR
} StatechartStates;


/*! Type declaration of the data structure for the StatechartIface interface scope. */
struct StatechartIface
{
	sc_boolean EVENT_JOY_UP_raised;
	sc_boolean EVENT_JOY_DOWN_raised;
	sc_boolean EVENT_JOY_LEFT_raised;
	sc_boolean EVENT_TIMEOUT_raised;
	sc_boolean EVENT_BUTTON1_EDGE_raised;
	sc_boolean EVENT_BUTTON1_raised;
	sc_boolean EVENT_BUTTON3_raised;
	sc_boolean LED_PERSONALIZADO_START_raised;
	sc_boolean LED_RECIENTE_START_raised;
	sc_boolean LED_DOBLE_START_raised;
	sc_boolean LED_LATTE_START_raised;
	sc_boolean LED_MOCHA_START_raised;
	sc_boolean EVENT_NONE_raised;
	sc_boolean secuencia_led_finalizado;
	sc_integer temp_actual;
	sc_integer temp_deseada;
	sc_integer nueva_temp;
	sc_integer idx;
	sc_integer distancia;
	sc_boolean eeprom_terminado;
	sc_boolean e;
};






/*! 
 * Type declaration of the data structure for the Statechart state machine.
 * This data structure has to be allocated by the client code. 
 */
struct Statechart
{
	StatechartStates stateConfVector[STATECHART_MAX_ORTHOGONAL_STATES];
	StatechartIface iface;
	sc_boolean isExecuting;
	statechart_eventqueue in_event_queue;
	statechart_event in_buffer[STATECHART_IN_EVENTQUEUE_BUFFERSIZE];
};



/*! Initializes the Statechart state machine data structures. Must be called before first usage.*/
extern void statechart_init(Statechart* handle);


/*! Activates the state machine. */
extern void statechart_enter(Statechart* handle);

/*! Deactivates the state machine. */
extern void statechart_exit(Statechart* handle);

/*! 
Can be used by the client code to trigger a run to completion step without raising an event.
*/
extern void statechart_trigger_without_event(Statechart* handle);



/*! Raises the in event 'EVENT_JOY_UP' that is defined in the default interface scope. */ 
extern void statechartIface_raise_eVENT_JOY_UP(Statechart* handle);
/*! Raises the in event 'EVENT_JOY_DOWN' that is defined in the default interface scope. */ 
extern void statechartIface_raise_eVENT_JOY_DOWN(Statechart* handle);
/*! Raises the in event 'EVENT_JOY_LEFT' that is defined in the default interface scope. */ 
extern void statechartIface_raise_eVENT_JOY_LEFT(Statechart* handle);
/*! Raises the in event 'EVENT_TIMEOUT' that is defined in the default interface scope. */ 
extern void statechartIface_raise_eVENT_TIMEOUT(Statechart* handle);
/*! Raises the in event 'EVENT_BUTTON1_EDGE' that is defined in the default interface scope. */ 
extern void statechartIface_raise_eVENT_BUTTON1_EDGE(Statechart* handle);
/*! Raises the in event 'EVENT_BUTTON1' that is defined in the default interface scope. */ 
extern void statechartIface_raise_eVENT_BUTTON1(Statechart* handle);
/*! Raises the in event 'EVENT_BUTTON3' that is defined in the default interface scope. */ 
extern void statechartIface_raise_eVENT_BUTTON3(Statechart* handle);
/*! Raises the in event 'LED_PERSONALIZADO_START' that is defined in the default interface scope. */ 
extern void statechartIface_raise_lED_PERSONALIZADO_START(Statechart* handle);
/*! Raises the in event 'LED_RECIENTE_START' that is defined in the default interface scope. */ 
extern void statechartIface_raise_lED_RECIENTE_START(Statechart* handle);
/*! Raises the in event 'LED_DOBLE_START' that is defined in the default interface scope. */ 
extern void statechartIface_raise_lED_DOBLE_START(Statechart* handle);
/*! Raises the in event 'LED_LATTE_START' that is defined in the default interface scope. */ 
extern void statechartIface_raise_lED_LATTE_START(Statechart* handle);
/*! Raises the in event 'LED_MOCHA_START' that is defined in the default interface scope. */ 
extern void statechartIface_raise_lED_MOCHA_START(Statechart* handle);
/*! Raises the in event 'EVENT_NONE' that is defined in the default interface scope. */ 
extern void statechartIface_raise_eVENT_NONE(Statechart* handle);
/*! Gets the value of the variable 'secuencia_led_finalizado' that is defined in the default interface scope. */ 
extern sc_boolean statechartIface_get_secuencia_led_finalizado(const Statechart* handle);
/*! Sets the value of the variable 'secuencia_led_finalizado' that is defined in the default interface scope. */ 
extern void statechartIface_set_secuencia_led_finalizado(Statechart* handle, sc_boolean value);
/*! Gets the value of the variable 'temp_actual' that is defined in the default interface scope. */ 
extern sc_integer statechartIface_get_temp_actual(const Statechart* handle);
/*! Sets the value of the variable 'temp_actual' that is defined in the default interface scope. */ 
extern void statechartIface_set_temp_actual(Statechart* handle, sc_integer value);
/*! Gets the value of the variable 'temp_deseada' that is defined in the default interface scope. */ 
extern sc_integer statechartIface_get_temp_deseada(const Statechart* handle);
/*! Sets the value of the variable 'temp_deseada' that is defined in the default interface scope. */ 
extern void statechartIface_set_temp_deseada(Statechart* handle, sc_integer value);
/*! Gets the value of the variable 'nueva_temp' that is defined in the default interface scope. */ 
extern sc_integer statechartIface_get_nueva_temp(const Statechart* handle);
/*! Sets the value of the variable 'nueva_temp' that is defined in the default interface scope. */ 
extern void statechartIface_set_nueva_temp(Statechart* handle, sc_integer value);
/*! Gets the value of the variable 'idx' that is defined in the default interface scope. */ 
extern sc_integer statechartIface_get_idx(const Statechart* handle);
/*! Sets the value of the variable 'idx' that is defined in the default interface scope. */ 
extern void statechartIface_set_idx(Statechart* handle, sc_integer value);
/*! Gets the value of the variable 'distancia' that is defined in the default interface scope. */ 
extern sc_integer statechartIface_get_distancia(const Statechart* handle);
/*! Sets the value of the variable 'distancia' that is defined in the default interface scope. */ 
extern void statechartIface_set_distancia(Statechart* handle, sc_integer value);
/*! Gets the value of the variable 'eeprom_terminado' that is defined in the default interface scope. */ 
extern sc_boolean statechartIface_get_eeprom_terminado(const Statechart* handle);
/*! Sets the value of the variable 'eeprom_terminado' that is defined in the default interface scope. */ 
extern void statechartIface_set_eeprom_terminado(Statechart* handle, sc_boolean value);
/*! Gets the value of the variable 'e' that is defined in the default interface scope. */ 
extern sc_boolean statechartIface_get_e(const Statechart* handle);
/*! Sets the value of the variable 'e' that is defined in the default interface scope. */ 
extern void statechartIface_set_e(Statechart* handle, sc_boolean value);

/*!
 * Checks whether the state machine is active (until 2.4.1 this method was used for states).
 * A state machine is active if it was entered. It is inactive if it has not been entered at all or if it has been exited.
 */
extern sc_boolean statechart_is_active(const Statechart* handle);

/*!
 * Checks if all active states are final. 
 * If there are no active states then the state machine is considered being inactive. In this case this method returns false.
 */
extern sc_boolean statechart_is_final(const Statechart* handle);

/*! Checks if the specified state is active (until 2.4.1 the used method for states was called isActive()). */
extern sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state);


#ifdef __cplusplus
}
#endif 

#endif /* STATECHART_H_ */
